# Only used for our GitHub CI/CD workflow, completely unrelated to hatch or the hatchlor.

name: test-env
channels:
  - conda-forge
dependencies:
  - python=3.10
  - cookiecutter
  - hatch
  - commitizen
  - pre-commit
  - typer
