default_context:
    full_name: "Harro Hatchlor"
    email: "harro@hatchlor.com"
    github_username: "hatchlor"
    project_name: "Hatchlor Enhanced demo project"
    project_slug: "hatchlor-enhanced-demo"
    project_short_description: "Python project featuring the Python project manager hatch powerd by The Hatchlor Enhanced."
    open_source_license: "proprietary"
    target_python_version: "3.10"
    project_repo: "https://github.com/dornech/the-hatchlor-enhanced-demo"
    pypi_username: "{{ cookiecutter.github_username }}"
    lock_file_support: false
